---
title: "Data Wrangling Best Practices - Historical Markers"
subtitle: "part two"
author: "fg"
date: "2023-07-21"
output: html_document
---



# Overview


This second part of the Lab is all about looking at words and ngrams.

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(tidytuesdayR)

```


# Load the weekly Data

Download the weekly data and make available in the `tt` object.


```{r Load}

tt <- tt_load("2023-07-04")

```


# Wrangle

Explore the data and process it, in order to manipulate the titles of the `historical_markers` dataset.
```{r Wrangle}

historical_markers <- tt$historical_markers
```



```{r}
df <- historical_markers%>%
  filter(!is.na(subtitle),!is.na(year_erected))%>%
  select(title,subtitle,addl_subtitle,year_erected,state_or_prov)%>%
  count(title,year_erected,state_or_prov,sort=T)

df %>%
  head
```


```{r}
titles <- df %>%
  select(title)%>%
  mutate(title=tolower(title),
         title = gsub("[[:punct:]]","",title),
         title = gsub("[[:digit:]]","",title)) #%>%
  # sample_frac(0.01) %>% head

titles_ch <- titles$title
```

```{r}
titles_ch[1]
```


## WordCloud df
```{r}
wordcloud_df <- tibble(word=strsplit(titles_ch, "\\s+")%>%unlist()) %>%
  count(word,sort=T) %>% # 6,273
  anti_join(tidytext::stop_words) %>% #6,066
  filter(!nchar(word)<=3) %>%
  mutate(prop=n/sum(n)*100) %>%
  # pull(prop)%>%summary()
  filter(prop>0.5)

wordcloud_df %>% head
```



## WordCloud
```{r}
library(wordcloud)

set.seed(000)
wordcloud_df %>%
  with(wordcloud(word,
                 freq= n,
                 colors = n,
                 fixed.asp = T)) 

```


## Save it!

Have a look at this article on Stackoverflow: <https://stackoverflow.com/questions/51759893/how-to-save-the-wordcloud-in-r>
```{r}

library(htmlwidgets)
saveWidget(wordcloud_df %>%
  with(wordcloud(word,
                 freq= n,
                 colors = n,
                 fixed.asp = T)) ,
  "1.html",
  selfcontained = F)

webshot::webshot("1.html","1.png",
                 vwidth = 1992, 
                 vheight = 1744, 
                 delay =10)
```



